FROM nginx:alpine
RUN apk add --no-cache wget unzip gettext
RUN wget https://github.com/gophish/gophish/releases/download/v0.12.1/gophish-v0.12.1-linux-64bit.zip -O /tmp/gophish.zip && \
    unzip /tmp/gophish.zip -d /app && \
    rm /tmp/gophish.zip
COPY config.json /app/config.json
COPY nginx.conf.template /etc/nginx/conf.d/default.conf.template
COPY start.sh /
RUN chmod +x /start.sh
CMD ["/start.sh"]